# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('hi', 'High'), ('lo', 'Low')], default='lo', max_length=10),
            preserve_default=False,
        ),
    ]
